INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (1, 'Argumento', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (2, 'Kakashi Gaiden y producciones originales del anime', 1, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (3, 'Aspectos de la serie', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (4, 'Personajes', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (5, 'Producción', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (6, 'Doblaje al español', 5, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (7, 'Contenido de la obra', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (8, 'Manga', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (9, 'Anime', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (10, 'Naruto', 9, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (11, 'Naruto: Shippūden', 9, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (12, 'Banda sonora', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (13, 'Animaciones originales', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (14, 'Naruto', 13, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (15, 'Naruto Shippuden', 13, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (16, 'Películas', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (17, 'Novelas', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (18, 'Secuela', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (19, 'Videojuegos', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (20, 'Juego de cartas', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (21, 'Artbooks y guías', 7, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (22, 'Recepción', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (23, 'Véase también', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (24, 'Referencias', null, null, null);
INSERT INTO public.series_trees (id, series_name, parent_id, created_at, updated_at) VALUES (25, 'Enlaces externos', null, null, null);